apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o config
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o config
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo/tempo.yml
          image: grafana/tempo
          name: tempo
          ports:
            - containerPort: 3200
            - containerPort: 9411
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/tempo
              name: tempo
            - mountPath: /etc/tempo
              subPath: docker/grafana
              name: tempo-claim
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: tempo
        - name: tempo-claim
          persistentVolumeClaim:
            claimName: nfs
