apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o config
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  ports:
    - name: "3200"
      port: 3200
      targetPort: 3200
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: tempo
status:
  loadBalancer: {}
