apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webhook
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: webhook
    spec:
      containers:
        - image: ubuntu:jammy
          command:
          - "sh"
          - "-c"
          - >
            apt update && apt install -y ncat && ncat --listen --keep-open --verbose --source-port 3333 --sh-exec 'tee /dev/tty | echo HTTP/1.1 200 OK\\r\\n'
          name: webhook
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: webhook
status:
  loadBalancer: {}
