apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/instance: nfs
  name: nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: admin
    spec:
      containers:
        - image: ubuntu:jammy
          command:
          - "sh"
          - "-c"
          - >
            while true; do
              sleep 3600;
            done
          name: admin
          volumeMounts:
#            - mountPath: /etc/tempo
#              subPath: docker/grafana
# kubectl cp docker/ admin-6bf759db5b-5px6s:/mnt
            - mountPath: /mnt
              name: claim
      restartPolicy: Always
      volumes:
        - name: claim
          persistentVolumeClaim:
            claimName: nfs
