apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o config
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o config
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      initContainers:
        - command:
            - sh
            - -c
            - |
              git clone --branch tap https://github.com/dsyer/teahouse.git /tmp/etc/config
          image: bitnami/git
          name: init
          volumeMounts:
            - mountPath: /tmp/etc
              name: config
      containers:
        - env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/grafana
              subPath: config/docker/grafana
              name: config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
